name: Release Java
run-name: Cut Release ${{github.event.inputs.release-version || github.ref_name}}
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true
on:
  push:
    # tags:
    #   - "v[0-9]+.[0-9]+.[0-9]+_java" # ex. v1.0.0_java

  workflow_dispatch:
    inputs:
      release-version:
        description: "Release version (v#.#.#[-rc#])+java"
        required: true

env:
  NEW_RELEASE_TAG_FROM_UI: ${{github.event.inputs.release-version}}
  NEW_RELEASE_TAG: ${{github.event.inputs.release-version || github.ref_name}}
  LATEST_FULL_RELEASE_TAG: _LATEST-FULL-RELEASE
  TEST_RUN: ${{contains(github.event.inputs.release-version || github.ref_name, '-rc')}}

jobs:
    build-artifacts:
      name: test
      runs-on: ubuntu-latest
      steps:
        - name: setup files
          run: |
            touch test1.sources.jar
            touch test1.jar
            ls

        - name: print event
          run: |
            echo ${{github.event}}
            echo ${{github.event_path}}
            cat  /home/runner/work/_temp/_github_workflow/event.json
            echo ${{github.event_name}}
